### PR TITLE
add kaaveh entry

### PR DESCRIPTION
**Pull request by Kaaveh**

### CODE REVIEW

**Comment by Kaaveh** [comment]
@KovalevAndrey Could you please review my PR?

**Comment by KovalevAndrey** [comment]
> @KovalevAndrey Could you please review my PR?

Hi @Kaaveh, can you pop at our booth, please? We don't accept remote PRs, and you can collect your raffle ticket as well

**Comment by Kaaveh** [comment]
> > @KovalevAndrey Could you please review my PR?
> 
> Hi @Kaaveh, can you pop at our booth, please? We don't accept remote PRs, and you can collect your raffle ticket as well

Right! Unfortunately, I'm not at conf. Thanks, BTW.

**Comment by KovalevAndrey** [comment]
> > > @KovalevAndrey Could you please review my PR?
> > 
> > 
> > Hi @Kaaveh, can you pop at our booth, please? We don't accept remote PRs, and you can collect your raffle ticket as well
> 
> Right! Unfortunately, I'm not at conf. Thanks, BTW.

No worries, if you can't make it, we'll make an exception since your content complies with the rules:)

**Comment by Kaaveh** [comment]
Thanks a lot @KovalevAndrey ! 🤩

**Pull request merged**
